import { Job } from '@/src/constants/interface/jobs'

export const dummyJobs: Job[] = [
  {
    id: 'JOB-001',
    clientName: 'Sarah Johnson',
    jobCategory: 'Plumbing',
    jobType: 'Leak Repair',
    distance: 2.3,
    revenue: 150,
    status: 'Scheduled',
  },
  {
    id: 'JOB-002',
    clientName: 'Mike Chen',
    jobCategory: 'HVAC',
    jobType: 'AC Installation',
    distance: 1.8,
    revenue: 450,
    status: 'In Progress',
  },
  {
    id: 'JOB-003',
    clientName: 'Lisa Rodriguez',
    jobCategory: 'Electrical',
    jobType: 'Outlet Repair',
    distance: 3.1,
    revenue: 120,
    status: 'Completed',
  },
  {
    id: 'JOB-004',
    clientName: 'David Wilson',
    jobCategory: 'Plumbing',
    jobType: 'Drain Cleaning',
    distance: 0.9,
    revenue: 200,
    status: 'Scheduled',
  },
  {
    id: 'JOB-005',
    clientName: 'Emma Thompson',
    jobCategory: 'HVAC',
    jobType: 'Heater Repair',
    distance: 4.2,
    revenue: 300,
    status: 'In Progress',
  },
  {
    id: 'JOB-006',
    clientName: 'James Brown',
    jobCategory: 'Electrical',
    jobType: 'Panel Upgrade',
    distance: 2.7,
    revenue: 800,
    status: 'Pending',
  },
  {
    id: 'JOB-007',
    clientName: 'Maria Garcia',
    jobCategory: 'Plumbing',
    jobType: 'Water Heater',
    distance: 1.5,
    revenue: 350,
    status: 'Scheduled',
  },
  {
    id: 'JOB-008',
    clientName: 'Robert Davis',
    jobCategory: 'HVAC',
    jobType: 'Duct Cleaning',
    distance: 3.8,
    revenue: 180,
    status: 'Completed',
  },
  {
    id: 'JOB-009',
    clientName: 'Jennifer Lee',
    jobCategory: 'Electrical',
    jobType: 'Lighting Install',
    distance: 2.1,
    revenue: 250,
    status: 'In Progress',
  },
  {
    id: 'JOB-010',
    clientName: 'Thomas Anderson',
    jobCategory: 'Plumbing',
    jobType: 'Pipe Repair',
    distance: 1.2,
    revenue: 175,
    status: 'Pending',
  },
]
