import { Job } from '@/src/constants/interface/jobs'

const baseJobs: Job[] = [
  {
    id: "J-2024-001",
    clientName: "Sarah Wilson",
    companyName: "Wilson Residence",
    phoneNumber: "+1 (555) 123-4567",
    email: "sarah.wilson@email.com",
    location: "123 Main St",
    city: "Houston",
    state: "TX",
    zipCode: "77001",
    jobCategory: "Plumbing",
    jobType: "Repair",
    jobDescription: "Kitchen sink clogged, water backing up into dishwasher",
    status: "In Progress",
    priority: "High",
    assignedTechnician: "Mike Rodriguez",
    technicianAvatar: "🔧",
    startDate: "2024-01-15",
    startTime: "09:00",
    estimatedDuration: "2 hours",
    actualStartTime: "09:15",
    estimatedEndTime: "11:15",
    source: "yelp",
    jobTags: ["urgent", "warranty"],
    noteTags: ["customer-notes"],
    distance: 2.3,
    revenue: 285.00,
    customerRating: 4.9,
    lastUpdated: "2024-01-15T10:30:00Z",
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
    photos: ["sink1.jpg", "sink2.jpg"],
    notes: "Customer mentioned this is the second time this month. May need to replace pipes.",
    partsNeeded: ["PVC pipe", "Drain cleaner"],
    specialInstructions: "Enter through back gate, dog in yard",
  },
  {
    id: "J-2024-016",
    clientName: "Mike Chen",
    companyName: "Chen Family Home",
    phoneNumber: "+1 (555) 987-6543",
    email: "mike.chen@email.com",
    location: "456 Oak Ave",
    city: "Houston",
    state: "TX",
    zipCode: "77002",
    jobCategory: "HVAC",
    jobType: "Maintenance",
    jobDescription: "Annual AC maintenance and filter replacement",
    status: "Scheduled",
    priority: "Medium",
    assignedTechnician: "Jennifer Lee",
    technicianAvatar: "⚡",
    startDate: "2024-01-15",
    startTime: "14:00",
    estimatedDuration: "1.5 hours",
    estimatedEndTime: "15:30",
    source: "website",
    jobTags: ["warranty"],
    noteTags: ["follow-up-required"],
    distance: 3.1,
    revenue: 195.00,
    customerRating: 4.8,
    lastUpdated: "2024-01-15T08:45:00Z",
    notes: "Customer prefers afternoon appointments",
    specialInstructions: "Park in driveway, ring doorbell twice",
  },
  {
    id: "J-2024-017",
    clientName: "Lisa Garcia",
    companyName: "Garcia Business Center",
    phoneNumber: "+1 (555) 456-7890",
    email: "lisa.garcia@business.com",
    location: "789 Business Blvd",
    city: "Houston",
    state: "TX",
    zipCode: "77003",
    jobCategory: "Electrical",
    jobType: "Installation",
    jobDescription: "Install new LED lighting system in office",
    status: "Pending",
    priority: "Low",
    assignedTechnician: "David Thompson",
    technicianAvatar: "⚡",
    startDate: "2024-01-16",
    startTime: "10:00",
    estimatedDuration: "4 hours",
    estimatedEndTime: "14:00",
    source: "referral",
    jobTags: ["commercial"],
    noteTags: ["equipment"],
    distance: 4.2,
    revenue: 850.00,
    customerRating: 5.0,
    lastUpdated: "2024-01-15T09:20:00Z",
    notes: "Large office space, need to coordinate with building management",
    partsNeeded: ["LED panels", "Wiring", "Dimmer switches"],
    specialInstructions: "Check in with security desk, building access required",
  },
  {
    id: "J-2024-018",
    clientName: "Robert Johnson",
    companyName: "Johnson Office",
    phoneNumber: "+1 (555) 321-6540",
    email: "robert.johnson@office.com",
    location: "321 Corporate Dr",
    city: "Houston",
    state: "TX",
    zipCode: "77004",
    jobCategory: "Plumbing",
    jobType: "Emergency",
    jobDescription: "Burst pipe in basement, water damage",
    status: "In Progress",
    priority: "High",
    assignedTechnician: "Mike Rodriguez",
    technicianAvatar: "🔧",
    startDate: "2024-01-15",
    startTime: "11:00",
    estimatedDuration: "3 hours",
    actualStartTime: "11:30",
    estimatedEndTime: "14:30",
    source: "phone",
    jobTags: ["urgent"],
    noteTags: ["insurance"],
    distance: 1.8,
    revenue: 450.00,
    customerRating: 4.7,
    lastUpdated: "2024-01-15T12:00:00Z",
    createdAt: "2024-01-15T10:45:00Z",
    updatedAt: "2024-01-15T12:00:00Z",
    notes: "Insurance claim filed, customer needs documentation",
    partsNeeded: ["Copper pipe", "Shut-off valve", "Drywall"],
    specialInstructions: "Emergency access through side door",
  },
  {
    id: "J-2024-019",
    clientName: "Emily Davis",
    companyName: "Davis Residence",
    phoneNumber: "+1 (555) 789-0123",
    email: "emily.davis@email.com",
    location: "654 Pine St",
    city: "Houston",
    state: "TX",
    zipCode: "77005",
    jobCategory: "HVAC",
    jobType: "Repair",
    jobDescription: "AC not cooling, thermostat issues",
    status: "Scheduled",
    priority: "Medium",
    assignedTechnician: "Jennifer Lee",
    technicianAvatar: "⚡",
    startDate: "2024-01-16",
    startTime: "13:00",
    estimatedDuration: "2 hours",
    estimatedEndTime: "15:00",
    source: "google-ads",
    jobTags: ["warranty"],
    noteTags: ["warranty"],
    distance: 2.7,
    revenue: 320.00,
    customerRating: 4.6,
    lastUpdated: "2024-01-15T10:15:00Z",
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-01-15T10:15:00Z",
    notes: "System under warranty, check if covered",
    partsNeeded: ["Thermostat", "Refrigerant"],
    specialInstructions: "Park on street, no driveway access",
  },
  {
    id: "J-2024-006",
    clientName: "James Wilson",
    companyName: "Wilson Manufacturing",
    phoneNumber: "+1 (555) 555-1234",
    email: "james.wilson@manufacturing.com",
    location: "987 Industrial Blvd",
    city: "Houston",
    state: "TX",
    zipCode: "77006",
    jobCategory: "Electrical",
    jobType: "Maintenance",
    jobDescription: "Monthly electrical system inspection",
    status: "Completed",
    priority: "Low",
    assignedTechnician: "David Thompson",
    technicianAvatar: "⚡",
    startDate: "2024-01-14",
    startTime: "08:00",
    estimatedDuration: "1 hour",
    actualStartTime: "08:15",
    estimatedEndTime: "09:15",
    actualEndTime: "09:30",
    source: "contract",
    jobTags: ["contract"],
    noteTags: ["routine"],
    distance: 5.1,
    revenue: 180.00,
    customerRating: 4.9,
    lastUpdated: "2024-01-14T09:30:00Z",
    createdAt: "2024-01-14T07:00:00Z",
    updatedAt: "2024-01-14T09:30:00Z",
    notes: "All systems operating normally",
    partsNeeded: [],
    specialInstructions: "Security clearance required, check in at front desk",
  },
  {
    id: "J-2024-007",
    clientName: "Maria Rodriguez",
    companyName: "Rodriguez Restaurant",
    phoneNumber: "+1 (555) 444-5678",
    email: "maria.rodriguez@restaurant.com",
    location: "555 Food Court",
    city: "Houston",
    state: "TX",
    zipCode: "77007",
    jobCategory: "Plumbing",
    jobType: "Installation",
    jobDescription: "Install commercial dishwasher",
    status: "Pending",
    priority: "Medium",
    assignedTechnician: "Mike Rodriguez",
    technicianAvatar: "🔧",
    startDate: "2024-01-17",
    startTime: "09:00",
    estimatedDuration: "5 hours",
    estimatedEndTime: "14:00",
    source: "referral",
    jobTags: ["commercial"],
    noteTags: ["equipment"],
    distance: 3.3,
    revenue: 1200.00,
    customerRating: 4.8,
    lastUpdated: "2024-01-15T11:45:00Z",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T11:45:00Z",
    notes: "Equipment delivered, ready for installation",
    partsNeeded: ["Commercial dishwasher", "Plumbing fittings"],
    specialInstructions: "Kitchen access through back door, coordinate with chef",
  },
  {
    id: "J-2024-008",
    clientName: "Thomas Brown",
    companyName: "Brown Residence",
    phoneNumber: "+1 (555) 666-7890",
    email: "thomas.brown@email.com",
    location: "777 Maple Ave",
    city: "Houston",
    state: "TX",
    zipCode: "77008",
    jobCategory: "HVAC",
    jobType: "Installation",
    jobDescription: "New furnace installation",
    status: "Scheduled",
    priority: "High",
    assignedTechnician: "Jennifer Lee",
    technicianAvatar: "⚡",
    startDate: "2024-01-16",
    startTime: "08:00",
    estimatedDuration: "6 hours",
    estimatedEndTime: "14:00",
    source: "website",
    jobTags: ["new-system"],
    noteTags: ["financing"],
    distance: 2.1,
    revenue: 2800.00,
    customerRating: 4.7,
    lastUpdated: "2024-01-15T14:20:00Z",
    createdAt: "2024-01-15T13:00:00Z",
    updatedAt: "2024-01-15T14:20:00Z",
    notes: "Customer approved financing, equipment ordered",
    partsNeeded: ["Furnace", "Ductwork", "Thermostat"],
    specialInstructions: "Early start, customer will be home all day",
  },
  {
    id: "J-2024-009",
    clientName: "Alex Thompson",
    companyName: "Thompson Residence",
    phoneNumber: "+1 (555) 777-8888",
    email: "alex.thompson@email.com",
    location: "888 Sunset Blvd",
    city: "Houston",
    state: "TX",
    zipCode: "77009",
    jobCategory: "Plumbing",
    jobType: "Emergency",
    jobDescription: "Burst pipe emergency call",
    status: "Submitted",
    priority: "High",
    assignedTechnician: "Mike Rodriguez",
    technicianAvatar: "🔧",
    startDate: "2024-01-15",
    startTime: "16:00",
    estimatedDuration: "2 hours",
    estimatedEndTime: "18:00",
    source: "phone",
    jobTags: ["urgent"],
    noteTags: ["insurance"],
    distance: 1.5,
    revenue: 350.00,
    customerRating: 4.5,
    lastUpdated: "2024-01-15T15:30:00Z",
    createdAt: "2024-01-15T15:00:00Z",
    updatedAt: "2024-01-15T15:30:00Z",
    notes: "Emergency call received, customer very distressed",
    partsNeeded: ["Copper pipe", "Shut-off valve"],
    specialInstructions: "Emergency access, customer waiting",
  },
  {
    id: "J-2024-010",
    clientName: "Rachel Green",
    companyName: "Green Office",
    phoneNumber: "+1 (555) 999-0000",
    email: "rachel.green@office.com",
    location: "999 Business Center",
    city: "Houston",
    state: "TX",
    zipCode: "77010",
    jobCategory: "Electrical",
    jobType: "Installation",
    jobDescription: "Office lighting upgrade",
    status: "Not Confirmed",
    priority: "Medium",
    assignedTechnician: "David Thompson",
    technicianAvatar: "⚡",
    startDate: "2024-01-17",
    startTime: "10:00",
    estimatedDuration: "6 hours",
    estimatedEndTime: "16:00",
    source: "website",
    jobTags: ["commercial"],
    noteTags: ["pending-confirmation"],
    distance: 4.5,
    revenue: 1200.00,
    customerRating: 4.8,
    lastUpdated: "2024-01-15T14:15:00Z",
    createdAt: "2024-01-15T13:45:00Z",
    updatedAt: "2024-01-15T14:15:00Z",
    notes: "Waiting for customer confirmation of appointment",
    partsNeeded: ["LED panels", "Wiring", "Dimmer switches"],
    specialInstructions: "Office hours only, coordinate with reception",
  },
  {
    id: "J-2024-011",
    clientName: "Monica Geller",
    companyName: "Geller Restaurant",
    phoneNumber: "+1 (555) 111-2222",
    email: "monica.geller@restaurant.com",
    location: "111 Food Street",
    city: "Houston",
    state: "TX",
    zipCode: "77011",
    jobCategory: "HVAC",
    jobType: "Repair",
    jobDescription: "Kitchen exhaust system repair",
    status: "Rejected",
    priority: "Low",
    assignedTechnician: "Jennifer Lee",
    technicianAvatar: "⚡",
    startDate: "2024-01-16",
    startTime: "11:00",
    estimatedDuration: "3 hours",
    estimatedEndTime: "14:00",
    source: "yelp",
    jobTags: ["commercial"],
    noteTags: ["customer-cancelled"],
    distance: 3.8,
    revenue: 450.00,
    customerRating: 4.2,
    lastUpdated: "2024-01-15T13:45:00Z",
    createdAt: "2024-01-15T12:30:00Z",
    updatedAt: "2024-01-15T13:45:00Z",
    notes: "Customer cancelled due to budget constraints",
    partsNeeded: ["Exhaust fan", "Ductwork"],
    specialInstructions: "Kitchen access through back door",
  },
  {
    id: "J-2024-012",
    clientName: "Chandler Bing",
    companyName: "Bing Residence",
    phoneNumber: "+1 (555) 333-4444",
    email: "chandler.bing@email.com",
    location: "333 Comedy Ave",
    city: "Houston",
    state: "TX",
    zipCode: "77012",
    jobCategory: "Plumbing",
    jobType: "Maintenance",
    jobDescription: "Annual plumbing inspection",
    status: "No Answer",
    priority: "Medium",
    assignedTechnician: "Mike Rodriguez",
    technicianAvatar: "🔧",
    startDate: "2024-01-16",
    startTime: "14:00",
    estimatedDuration: "1 hour",
    estimatedEndTime: "15:00",
    source: "referral",
    jobTags: ["contract"],
    noteTags: ["no-response"],
    distance: 2.2,
    revenue: 150.00,
    customerRating: 4.6,
    lastUpdated: "2024-01-15T12:30:00Z",
    createdAt: "2024-01-15T11:15:00Z",
    updatedAt: "2024-01-15T12:30:00Z",
    notes: "Customer not responding to calls or messages",
    partsNeeded: [],
    specialInstructions: "Call before arrival",
  },
  {
    id: "J-2024-013",
    clientName: "Joey Tribbiani",
    companyName: "Tribbiani Apartment",
    phoneNumber: "+1 (555) 555-6666",
    email: "joey.tribbiani@email.com",
    location: "555 Actor Lane",
    city: "Houston",
    state: "TX",
    zipCode: "77013",
    jobCategory: "Electrical",
    jobType: "Emergency",
    jobDescription: "Power outage in apartment",
    status: "Canceled",
    priority: "High",
    assignedTechnician: "David Thompson",
    technicianAvatar: "⚡",
    startDate: "2024-01-15",
    startTime: "20:00",
    estimatedDuration: "2 hours",
    estimatedEndTime: "22:00",
    source: "phone",
    jobTags: ["urgent"],
    noteTags: ["customer-cancelled"],
    distance: 1.9,
    revenue: 300.00,
    customerRating: 4.3,
    lastUpdated: "2024-01-15T19:30:00Z",
    createdAt: "2024-01-15T19:00:00Z",
    updatedAt: "2024-01-15T19:30:00Z",
    notes: "Customer cancelled - building management resolved issue",
    partsNeeded: ["Circuit breaker", "Wiring"],
    specialInstructions: "Apartment access through main entrance",
  },
  {
    id: "J-2024-014",
    clientName: "Phoebe Buffay",
    companyName: "Buffay Residence",
    phoneNumber: "+1 (555) 777-9999",
    email: "phoebe.buffay@email.com",
    location: "777 Music Street",
    city: "Houston",
    state: "TX",
    zipCode: "77014",
    jobCategory: "HVAC",
    jobType: "Installation",
    jobDescription: "New AC unit installation",
    status: "Confirmed",
    priority: "Medium",
    assignedTechnician: "Jennifer Lee",
    technicianAvatar: "⚡",
    startDate: "2024-01-18",
    startTime: "09:00",
    estimatedDuration: "4 hours",
    estimatedEndTime: "13:00",
    source: "website",
    jobTags: ["new-system"],
    noteTags: ["confirmed", "called"],
    distance: 3.1,
    revenue: 2200.00,
    customerRating: 4.9,
    lastUpdated: "2024-01-15T16:20:00Z",
    createdAt: "2024-01-15T15:45:00Z",
    updatedAt: "2024-01-15T16:20:00Z",
    notes: "Customer confirmed appointment and payment method",
    partsNeeded: ["AC unit", "Thermostat", "Ductwork"],
    specialInstructions: "Early start, customer will be home",
  },
  {
    id: "J-2024-015",
    clientName: "Ross Geller",
    companyName: "Geller Museum",
    phoneNumber: "+1 (555) 888-1111",
    email: "ross.geller@museum.com",
    location: "888 Museum Drive",
    city: "Houston",
    state: "TX",
    zipCode: "77015",
    jobCategory: "Electrical",
    jobType: "Maintenance",
    jobDescription: "Museum lighting system maintenance",
    status: "Follow Up",
    priority: "Low",
    assignedTechnician: "David Thompson",
    technicianAvatar: "⚡",
    startDate: "2024-01-19",
    startTime: "10:00",
    estimatedDuration: "3 hours",
    estimatedEndTime: "13:00",
    source: "contract",
    jobTags: ["contract"],
    noteTags: ["follow-up-required"],
    distance: 5.2,
    revenue: 400.00,
    customerRating: 4.7,
    lastUpdated: "2024-01-15T17:45:00Z",
    createdAt: "2024-01-15T17:00:00Z",
    updatedAt: "2024-01-15T17:45:00Z",
    notes: "Need to follow up on contract renewal",
    partsNeeded: ["Light bulbs", "Wiring"],
    specialInstructions: "Security clearance required, check in at front desk",
  },
  {
    id: "J-2024-002",
    clientName: "Mike Chen",
    companyName: "Chen Family Home",
    phoneNumber: "+1 (555) 987-6543",
    email: "mike.chen@email.com",
    location: "456 Oak Ave",
    city: "Houston",
    state: "TX",
    zipCode: "77002",
    jobCategory: "HVAC",
    jobType: "Maintenance",
    jobDescription: "Annual AC maintenance and filter replacement",
    status: "Scheduled",
    priority: "Medium",
    assignedTechnician: "Jennifer Lee",
    technicianAvatar: "⚡",
    startDate: "2024-01-15",
    startTime: "14:00",
    estimatedDuration: "1.5 hours",
    estimatedEndTime: "15:30",
    source: "website",
    jobTags: ["warranty"],
    noteTags: ["follow-up-required"],
    distance: 3.1,
    revenue: 195.00,
    customerRating: 4.8,
    lastUpdated: "2024-01-15T08:45:00Z",
    notes: "Customer prefers afternoon appointments",
    specialInstructions: "Park in driveway, ring doorbell twice",
  },
  {
    id: "J-2024-003",
    clientName: "Lisa Garcia",
    companyName: "Garcia Business Center",
    phoneNumber: "+1 (555) 456-7890",
    email: "lisa.garcia@business.com",
    location: "789 Business Blvd",
    city: "Houston",
    state: "TX",
    zipCode: "77003",
    jobCategory: "Electrical",
    jobType: "Installation",
    jobDescription: "Install new LED lighting system in office",
    status: "Pending",
    priority: "Low",
    assignedTechnician: "David Thompson",
    technicianAvatar: "⚡",
    startDate: "2024-01-16",
    startTime: "10:00",
    estimatedDuration: "4 hours",
    estimatedEndTime: "14:00",
    source: "referral",
    jobTags: ["commercial"],
    noteTags: ["equipment"],
    distance: 4.2,
    revenue: 850.00,
    customerRating: 5.0,
    lastUpdated: "2024-01-15T09:20:00Z",
    notes: "Large office space, need to coordinate with building management",
    partsNeeded: ["LED panels", "Wiring", "Dimmer switches"],
    specialInstructions: "Check in with security desk, building access required",
  },
  {
    id: "J-2024-004",
    clientName: "Robert Johnson",
    companyName: "Johnson Residence",
    phoneNumber: "+1 (555) 321-6547",
    email: "robert.johnson@email.com",
    location: "321 Pine St",
    city: "Houston",
    state: "TX",
    zipCode: "77004",
    jobCategory: "Plumbing",
    jobType: "Emergency",
    jobDescription: "Burst pipe in basement, water damage",
    status: "Urgent",
    priority: "Critical",
    assignedTechnician: "Mike Rodriguez",
    technicianAvatar: "🔧",
    startDate: "2024-01-15",
    startTime: "ASAP",
    estimatedDuration: "3 hours",
    actualStartTime: "11:30",
    estimatedEndTime: "14:30",
    source: "phone",
    jobTags: ["urgent"],
    noteTags: ["safety-concern"],
    distance: 1.8,
    revenue: 450.00,
    customerRating: 4.7,
    lastUpdated: "2024-01-15T11:30:00Z",
    notes: "Water shut off at main valve, customer very distressed",
    partsNeeded: ["Copper pipe", "Pipe fittings", "Water damage equipment"],
    specialInstructions: "Emergency access - customer will meet at door",
  },
  {
    id: "J-2024-005",
    clientName: "Emily Davis",
    companyName: "Davis Apartment",
    phoneNumber: "+1 (555) 789-0123",
    email: "emily.davis@email.com",
    location: "654 Apartment Dr, Unit 5B",
    city: "Houston",
    state: "TX",
    zipCode: "77005",
    jobCategory: "HVAC",
    jobType: "Repair",
    jobDescription: "AC not cooling, thermostat issues",
    status: "Completed",
    priority: "Medium",
    assignedTechnician: "Jennifer Lee",
    technicianAvatar: "⚡",
    startDate: "2024-01-14",
    startTime: "13:00",
    estimatedDuration: "2 hours",
    actualStartTime: "13:15",
    actualEndTime: "15:00",
    source: "google-ads",
    jobTags: ["warranty"],
    noteTags: ["customer-notes"],
    distance: 2.7,
    revenue: 320.00,
    customerRating: 5.0,
    lastUpdated: "2024-01-14T15:00:00Z",
    notes: "Thermostat battery replaced, AC filter cleaned, system working properly",
    partsNeeded: ["Thermostat batteries", "AC filter"],
    specialInstructions: "Apartment complex, parking in visitor spots",
  },
]

const pad = (num: number) => num.toString().padStart(2, '0')

export const dummyJobs: Job[] = baseJobs.map((job, idx) => {
  const now = new Date()
  const year = now.getFullYear()
  const month = now.getMonth() + 1 // 1-based
  const day = Math.min(idx + 1, 28) // keep within month

  return {
    ...job,
    // Always use today's date for startDate so demo data stays current
    startDate: now.toISOString().split('T')[0],
  }
})