import { JobTagNote } from '@/src/constants/interface/jobTagNotes'

export const dummyJobTagNotes: JobTagNote[] = [
  {
    _id: '1',
    title: 'Customer Welcome Script',
    content:
      "Hello! Thank you for choosing our services. My name is [Name] and I'll be assisting you today. How may I help you with your [service type] needs?",
    type: 'script',
    category: 'Customer Service',
    tags: ['welcome', 'introduction', 'customer service'],
    is_active: true,
    is_public: true,
    usage_count: 156,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-15T14:30:00Z',
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-01-15T14:30:00Z',
  },
  {
    _id: '2',
    title: 'Emergency Service Protocol',
    content:
      'For emergency service calls: 1) Assess safety immediately 2) Contact emergency services if needed 3) Document incident details 4) Notify supervisor 5) Follow up within 24 hours',
    type: 'note',
    category: 'Emergency Procedures',
    tags: ['emergency', 'safety', 'protocol', 'urgent'],
    is_active: true,
    is_public: false,
    usage_count: 23,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-14T08:15:00Z',
    createdAt: '2024-01-05T11:30:00Z',
    updatedAt: '2024-01-14T08:15:00Z',
  },
  {
    _id: '3',
    title: 'Invoice Collection Template',
    content:
      'Dear [Customer Name],\n\nThis is a friendly reminder that invoice #[Invoice Number] for [Amount] is due on [Due Date]. Please process payment at your earliest convenience.\n\nThank you for your business.\n\nBest regards,\n[Company Name]',
    type: 'template',
    category: 'Billing',
    tags: ['invoice', 'payment', 'reminder', 'billing'],
    is_active: true,
    is_public: true,
    usage_count: 89,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-13T16:45:00Z',
    createdAt: '2024-01-08T14:20:00Z',
    updatedAt: '2024-01-13T16:45:00Z',
  },
  {
    _id: '4',
    title: 'Quality Inspection Checklist',
    content:
      'Pre-service: Equipment check, safety gear, customer requirements review\nDuring service: Follow procedures, document progress, quality checks\nPost-service: Final inspection, customer approval, cleanup verification',
    type: 'note',
    category: 'Quality Control',
    tags: ['quality', 'inspection', 'checklist', 'procedures'],
    is_active: true,
    is_public: true,
    usage_count: 234,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-15T12:20:00Z',
    createdAt: '2024-01-03T10:15:00Z',
    updatedAt: '2024-01-15T12:20:00Z',
  },
  {
    _id: '5',
    title: 'Follow-up Call Script',
    content:
      "Hi [Customer Name], this is [Name] from [Company]. I'm calling to follow up on the [service] we completed on [date]. How is everything working? Do you have any questions or concerns?",
    type: 'script',
    category: 'Customer Service',
    tags: ['follow-up', 'customer service', 'satisfaction'],
    is_active: true,
    is_public: true,
    usage_count: 178,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-14T15:30:00Z',
    createdAt: '2024-01-06T13:45:00Z',
    updatedAt: '2024-01-14T15:30:00Z',
  },
  {
    _id: '6',
    title: 'New Customer Onboarding',
    content:
      'Welcome package includes: service overview, contact information, emergency procedures, warranty information, maintenance schedule, and customer portal access instructions.',
    type: 'note',
    category: 'Customer Onboarding',
    tags: ['onboarding', 'new customer', 'welcome', 'information'],
    is_active: true,
    is_public: false,
    usage_count: 67,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-12T11:00:00Z',
    createdAt: '2024-01-02T16:30:00Z',
    updatedAt: '2024-01-12T11:00:00Z',
  },
  {
    _id: '7',
    title: 'Complaint Resolution Script',
    content:
      'I understand your concern and I apologize for the inconvenience. Let me help resolve this issue. Can you please provide more details about what happened? I want to ensure we address this properly.',
    type: 'script',
    category: 'Customer Service',
    tags: ['complaint', 'resolution', 'apology', 'customer service'],
    is_active: true,
    is_public: true,
    usage_count: 45,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-11T14:20:00Z',
    createdAt: '2024-01-07T09:15:00Z',
    updatedAt: '2024-01-11T14:20:00Z',
  },
  {
    _id: '8',
    title: 'Maintenance Schedule Template',
    content:
      'Maintenance Due Notice\n\nCustomer: [Customer Name]\nService: [Service Type]\nDue Date: [Due Date]\nEstimated Duration: [Duration]\nTechnician: [Technician Name]\n\nPlease contact us to schedule.',
    type: 'template',
    category: 'Maintenance',
    tags: ['maintenance', 'schedule', 'reminder', 'service'],
    is_active: true,
    is_public: true,
    usage_count: 123,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-10T10:30:00Z',
    createdAt: '2024-01-04T12:00:00Z',
    updatedAt: '2024-01-10T10:30:00Z',
  },
  {
    _id: '9',
    title: 'Safety Protocol Reminder',
    content:
      'Always wear appropriate PPE, check equipment before use, follow lockout/tagout procedures, maintain clean work area, and report any safety concerns immediately.',
    type: 'note',
    category: 'Safety',
    tags: ['safety', 'PPE', 'equipment', 'procedures'],
    is_active: true,
    is_public: true,
    usage_count: 456,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-15T09:45:00Z',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-15T09:45:00Z',
  },
  {
    _id: '10',
    title: 'Appointment Confirmation',
    content:
      'Hi [Customer Name], this confirms your appointment for [service] on [date] at [time]. Our technician [Name] will arrive within the scheduled window. Please ensure access to the service area.',
    type: 'template',
    category: 'Scheduling',
    tags: ['appointment', 'confirmation', 'scheduling', 'reminder'],
    is_active: true,
    is_public: true,
    usage_count: 298,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-15T13:15:00Z',
    createdAt: '2024-01-09T15:30:00Z',
    updatedAt: '2024-01-15T13:15:00Z',
  },
  {
    _id: '11',
    title: 'Warranty Information',
    content:
      'Standard warranty covers parts and labor for 1 year. Extended warranty available for 2-5 years. Exclusions: normal wear, misuse, unauthorized modifications. Contact service department for claims.',
    type: 'note',
    category: 'Warranty',
    tags: ['warranty', 'coverage', 'exclusions', 'claims'],
    is_active: true,
    is_public: true,
    usage_count: 134,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-13T17:00:00Z',
    createdAt: '2024-01-06T10:45:00Z',
    updatedAt: '2024-01-13T17:00:00Z',
  },
  {
    _id: '12',
    title: 'Service Completion Script',
    content:
      "I've completed the [service] as requested. Everything is working properly now. Here's what I did: [brief description]. Do you have any questions? Please sign the work order to confirm completion.",
    type: 'script',
    category: 'Service Completion',
    tags: ['completion', 'service', 'confirmation', 'work order'],
    is_active: true,
    is_public: true,
    usage_count: 267,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-15T16:45:00Z',
    createdAt: '2024-01-05T14:20:00Z',
    updatedAt: '2024-01-15T16:45:00Z',
  },
  {
    _id: '13',
    title: 'Pricing Explanation',
    content:
      'Our pricing includes: labor, parts, materials, and warranty. Additional charges may apply for: after-hours service, emergency calls, special equipment, or extended travel. All prices quoted in advance.',
    type: 'note',
    category: 'Pricing',
    tags: ['pricing', 'labor', 'parts', 'charges'],
    is_active: true,
    is_public: true,
    usage_count: 89,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-12T14:30:00Z',
    createdAt: '2024-01-08T11:15:00Z',
    updatedAt: '2024-01-12T14:30:00Z',
  },
  {
    _id: '14',
    title: 'Customer Feedback Request',
    content:
      'We value your feedback! Please take a moment to rate our service and provide comments. Your input helps us improve and maintain quality standards. Survey link: [link] or call [number].',
    type: 'template',
    category: 'Feedback',
    tags: ['feedback', 'survey', 'rating', 'improvement'],
    is_active: true,
    is_public: true,
    usage_count: 156,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-14T18:20:00Z',
    createdAt: '2024-01-07T13:00:00Z',
    updatedAt: '2024-01-14T18:20:00Z',
  },
  {
    _id: '15',
    title: 'Equipment Troubleshooting',
    content:
      'Common issues: power supply, connections, settings, filters, maintenance schedule. Check basics first: power, switches, connections. Refer to manual or contact technical support if needed.',
    type: 'note',
    category: 'Troubleshooting',
    tags: ['troubleshooting', 'equipment', 'issues', 'support'],
    is_active: true,
    is_public: false,
    usage_count: 78,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-11T12:45:00Z',
    createdAt: '2024-01-04T09:30:00Z',
    updatedAt: '2024-01-11T12:45:00Z',
  },
  {
    _id: '16',
    title: 'Rescheduling Request',
    content:
      'I need to reschedule my appointment for [service] from [original date/time] to [new date/time]. Reason: [reason]. Please confirm the new time works for your schedule.',
    type: 'template',
    category: 'Scheduling',
    tags: ['reschedule', 'appointment', 'change', 'scheduling'],
    is_active: true,
    is_public: true,
    usage_count: 45,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-10T15:15:00Z',
    createdAt: '2024-01-09T16:45:00Z',
    updatedAt: '2024-01-10T15:15:00Z',
  },
  {
    _id: '17',
    title: 'Service Area Preparation',
    content:
      'Before service: clear access to equipment, remove obstacles, secure pets, ensure power/water available, provide parking if needed, and have someone available for questions.',
    type: 'note',
    category: 'Service Preparation',
    tags: ['preparation', 'access', 'equipment', 'safety'],
    is_active: true,
    is_public: true,
    usage_count: 189,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-15T11:30:00Z',
    createdAt: '2024-01-03T14:15:00Z',
    updatedAt: '2024-01-15T11:30:00Z',
  },
  {
    _id: '18',
    title: 'Payment Collection Script',
    content:
      'Thank you for choosing our services. The total amount is [amount]. We accept cash, check, credit cards, and online payments. Would you like a receipt? Do you have any questions about the charges?',
    type: 'script',
    category: 'Payment',
    tags: ['payment', 'collection', 'receipt', 'charges'],
    is_active: true,
    is_public: true,
    usage_count: 234,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-14T16:00:00Z',
    createdAt: '2024-01-06T12:30:00Z',
    updatedAt: '2024-01-14T16:00:00Z',
  },
  {
    _id: '19',
    title: 'Customer Portal Instructions',
    content:
      'Access your account at [portal URL]. Features: view service history, schedule appointments, pay invoices, request maintenance, update contact information, and download documents.',
    type: 'note',
    category: 'Customer Portal',
    tags: ['portal', 'account', 'online', 'self-service'],
    is_active: true,
    is_public: true,
    usage_count: 167,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-13T19:45:00Z',
    createdAt: '2024-01-05T15:00:00Z',
    updatedAt: '2024-01-13T19:45:00Z',
  },
  {
    _id: '20',
    title: 'Emergency Contact Information',
    content:
      'Emergency Service: [24/7 number]\nRegular Service: [business hours number]\nAfter Hours: [emergency number]\nEmail: [email]\nOnline: [portal URL]\n\nFor life-threatening emergencies, call 911.',
    type: 'template',
    category: 'Emergency',
    tags: ['emergency', 'contact', '24/7', 'urgent'],
    is_active: true,
    is_public: true,
    usage_count: 89,
    created_by: 'admin@wepro.com',
    last_used: '2024-01-12T20:30:00Z',
    createdAt: '2024-01-08T17:15:00Z',
    updatedAt: '2024-01-12T20:30:00Z',
  },
]
