import { Package } from '@/src/constants/interface/package'

export const dummyPackages: Package[] = [
  {
    _id: '1',
    name: 'Starter Package',
    type: 'P2',
    interval: 'monthly',
    price: 29.99,
    limits: {
      users: 5,
      numbers: 3,
      minutes: 1000,
      sms: 5000,
      whatsappSms: 2000,
      emails: 5000,
    },
    additionalPricing: {
      userMonthly: 15.0,
      numberMonthly: 5.0,
      perMinute: 0.1,
      perSms: 0.02,
      perWhatsappSms: 0.02,
      perEmail: 0.01,
    },
    createdBy: 'admin123',
    createdAt: '2024-01-15',
    modules: [
      { _id: 'm1', packageId: '1', moduleCode: 'M1' },
      { _id: 'm2', packageId: '1', moduleCode: 'M2' },
      { _id: 'm3', packageId: '1', moduleCode: 'M3' },
    ],
  },
  {
    _id: '2',
    name: 'Professional Package',
    type: 'P3',
    interval: 'monthly',
    price: 79.99,
    limits: {
      users: 15,
      numbers: 8,
      minutes: 5000,
      sms: 25000,
      whatsappSms: 10000,
      emails: 25000,
    },
    additionalPricing: {
      userMonthly: 25.0,
      numberMonthly: 3.0,
      perMinute: 0.08,
      perSms: 0.015,
      perWhatsappSms: 0.015,
      perEmail: 0.008,
    },
    createdBy: 'admin123',
    createdAt: '2024-01-20',
    modules: [
      { _id: 'm4', packageId: '2', moduleCode: 'M1' },
      { _id: 'm5', packageId: '2', moduleCode: 'M2' },
      { _id: 'm6', packageId: '2', moduleCode: 'M3' },
      { _id: 'm7', packageId: '2', moduleCode: 'M4' },
      { _id: 'm8', packageId: '2', moduleCode: 'M5' },
    ],
  },
  {
    _id: '3',
    name: 'Enterprise Package',
    type: 'P4',
    interval: 'Yearly',
    price: 1999.99,
    limits: {
      users: 50,
      numbers: 25,
      minutes: 20000,
      sms: 100000,
      whatsappSms: 50000,
      emails: 100000,
    },
    additionalPricing: {
      userMonthly: 32.0,
      numberMonthly: 2.0,
      perMinute: 0.06,
      perSms: 0.01,
      perWhatsappSms: 0.01,
      perEmail: 0.01,
    },
    createdBy: 'admin123',
    createdAt: '2024-02-01',
    modules: [
      { _id: 'm9', packageId: '3', moduleCode: 'M1' },
      { _id: 'm10', packageId: '3', moduleCode: 'M2' },
      { _id: 'm11', packageId: '3', moduleCode: 'M3' },
      { _id: 'm12', packageId: '3', moduleCode: 'M4' },
      { _id: 'm13', packageId: '3', moduleCode: 'M5' },
      { _id: 'm14', packageId: '3', moduleCode: 'M6' },
      { _id: 'm15', packageId: '3', moduleCode: 'M7' },
      { _id: 'm16', packageId: '3', moduleCode: 'M8' },
    ],
  },
  {
    _id: '4',
    name: 'Weekly Trial',
    type: 'P2',
    interval: 'Weekly',
    price: 9.99,
    limits: {
      users: 2,
      numbers: 1,
      minutes: 500,
      sms: 1000,
      whatsappSms: 500,
      emails: 1000,
    },
    additionalPricing: {
      userMonthly: 20.0,
      numberMonthly: 8.0,
      perMinute: 0.12,
      perSms: 0.025,
      perWhatsappSms: 0.025,
      perEmail: 0.015,
    },
    createdBy: 'admin123',
    createdAt: '2024-02-10',
    modules: [
      { _id: 'm17', packageId: '4', moduleCode: 'M1' },
      { _id: 'm18', packageId: '4', moduleCode: 'M2' },
    ],
  },
  {
    _id: '5',
    name: 'Premium Annual',
    type: 'P3',
    interval: 'Yearly',
    price: 799.99,
    limits: {
      users: 25,
      numbers: 12,
      minutes: 15000,
      sms: 75000,
      whatsappSms: 30000,
      emails: 75000,
    },
    additionalPricing: {
      userMonthly: 28.0,
      numberMonthly: 2.5,
      perMinute: 0.07,
      perSms: 0.012,
      perWhatsappSms: 0.012,
      perEmail: 0.009,
    },
    createdBy: 'admin123',
    createdAt: '2024-02-15',
    modules: [
      { _id: 'm19', packageId: '5', moduleCode: 'M1' },
      { _id: 'm20', packageId: '5', moduleCode: 'M2' },
      { _id: 'm21', packageId: '5', moduleCode: 'M3' },
      { _id: 'm22', packageId: '5', moduleCode: 'M4' },
      { _id: 'm23', packageId: '5', moduleCode: 'M5' },
      { _id: 'm24', packageId: '5', moduleCode: 'M6' },
    ],
  },
  {
    _id: '6',
    name: 'Basic Starter',
    type: 'P2',
    interval: 'monthly',
    price: 19.99,
    limits: {
      users: 3,
      numbers: 2,
      minutes: 500,
      sms: 2000,
      whatsappSms: 1000,
      emails: 2000,
    },
    additionalPricing: {
      userMonthly: 18.0,
      numberMonthly: 6.0,
      perMinute: 0.11,
      perSms: 0.022,
      perWhatsappSms: 0.022,
      perEmail: 0.012,
    },
    createdBy: 'admin123',
    createdAt: '2024-02-20',
    modules: [{ _id: 'm25', packageId: '6', moduleCode: 'M1' }],
  },
]

export const dummyModules = [
  { value: 'M1', label: 'Module 1 - Core Features' },
  { value: 'M2', label: 'Module 2 - Advanced Analytics' },
  { value: 'M3', label: 'Module 3 - Admin Team' },
  { value: 'M4', label: 'Module 4 - API Access' },
  { value: 'M5', label: 'Module 5 - White Label' },
  { value: 'M6', label: 'Module 6 - Custom Integrations' },
  { value: 'M7', label: 'Module 7 - Advanced Reporting' },
  { value: 'M8', label: 'Module 8 - Enterprise Features' },
  { value: 'M9', label: 'Module 9 - Priority Support' },
  { value: 'M10', label: 'Module 10 - Dedicated Manager' },
]
