import { JobSchedule } from "../interface/jobSchedule";

export const jobsSchedules:JobSchedule[] = [
    {
      id: "J001",
      title: "HVAC System Repair",
      client: "Johnson Residence",
      clientPhone: "(555) 123-4567",
      address: "123 Main St, Houston, TX 77001",
      technician: "Mike Rodriguez",
      technicianId: "T001",
      status: "scheduled",
      jobType: "HVAC",
      estimatedDuration: 120, // minutes
      scheduledDate: "2025-10-15",
      scheduledTime: "09:00",
      endTime: "11:00",
      value: 450.00,
      description: "AC unit not cooling properly, needs diagnostic and repair",
      tags: ["Emergency", "Residential"],
      source: "Google Ads",
      complexity: "medium",
      metroArea: "Houston Metro",
      notes: "Customer prefers morning appointments"
    },
    {
      id: "J002", 
      title: "Plumbing Leak Repair",
      client: "Smith Commercial",
      clientPhone: "(555) 987-6543",
      address: "456 Oak Ave, Houston, TX 77002",
      technician: "Sarah Wilson",
      technicianId: "T002",
      status: "in-progress",
      jobType: "Plumbing",
      estimatedDuration: 90,
      scheduledDate: "2025-10-15",
      scheduledTime: "10:30",
      endTime: "12:00",
      value: 320.00,
      description: "Water leak in main office bathroom",
      tags: ["Commercial", "Urgent"],
      source: "Direct Call",
      complexity: "simple",
      metroArea: "Houston Metro",
      notes: "Building manager on-site"
    },
    {
      id: "J003",
      title: "Electrical Panel Upgrade",
      client: "Brown Family",
      clientPhone: "(555) 456-7890",
      address: "789 Pine St, Houston, TX 77003",
      technician: "David Chen",
      technicianId: "T003",
      status: "completed",
      jobType: "Electrical",
      estimatedDuration: 180,
      scheduledDate: "2025-10-15",
      scheduledTime: "13:00",
      endTime: "16:00",
      value: 850.00,
      description: "Upgrade electrical panel to 200 amp service",
      tags: ["Residential", "Upgrade"],
      source: "Referral",
      complexity: "complex",
      metroArea: "Houston Metro",
      notes: "Permit required - already obtained"
    },
    {
      id: "J004",
      title: "Garage Door Installation",
      client: "Wilson Corp",
      clientPhone: "(555) 321-9876",
      address: "321 Elm Dr, Houston, TX 77004",
      technician: "Lisa Garcia",
      technicianId: "T004",
      status: "scheduled",
      jobType: "Installation",
      estimatedDuration: 150,
      scheduledDate: "2025-10-16",
      scheduledTime: "08:00",
      endTime: "10:30",
      value: 680.00,
      description: "Install new automatic garage door with opener",
      tags: ["Commercial", "Installation"],
      source: "Website",
      complexity: "medium",
      metroArea: "Houston Metro",
      notes: "Corporate client - priority service"
    },
    {
      id: "J005",
      title: "Kitchen Sink Repair",
      client: "Davis Residence",
      clientPhone: "(555) 654-3210",
      address: "654 Maple Ln, Houston, TX 77005",
      technician: "Unassigned",
      technicianId: null,
      status: "unassigned",
      jobType: "Plumbing",
      estimatedDuration: 60,
      scheduledDate: "2025-10-16",
      scheduledTime: "14:00",
      endTime: "15:00",
      value: 180.00,
      description: "Kitchen sink faucet leaking, needs replacement",
      tags: ["Residential"],
      source: "Yelp",
      complexity: "simple",
      metroArea: "Houston Metro",
      notes: "Senior citizen discount applied"
    },
    {
      id: "J006",
      title: "AC Maintenance",
      client: "Martinez Office",
      clientPhone: "(555) 111-2222",
      address: "111 Business Blvd, Houston, TX 77006",
      technician: "Mike Rodriguez",
      technicianId: "T001",
      status: "scheduled",
      jobType: "HVAC",
      estimatedDuration: 90,
      scheduledDate: "2025-10-14",
      scheduledTime: "09:00",
      endTime: "10:30",
      value: 280.00,
      description: "Routine HVAC maintenance and filter replacement",
      tags: ["Commercial", "Maintenance"],
      source: "Contract",
      complexity: "simple",
      metroArea: "Houston Metro",
      notes: "Monthly service contract"
    },
    {
      id: "J007",
      title: "Emergency Electrical",
      client: "Thompson Home",
      clientPhone: "(555) 333-4444",
      address: "333 Cedar St, Houston, TX 77007",
      technician: "David Chen",
      technicianId: "T003",
      status: "urgent",
      jobType: "Electrical",
      estimatedDuration: 60,
      scheduledDate: "2025-10-13",
      scheduledTime: "15:00",
      endTime: "16:00",
      value: 380.00,
      description: "Power outage in main electrical panel",
      tags: ["Emergency", "Residential"],
      source: "Emergency Call",
      complexity: "medium",
      metroArea: "Greater Houston",
      notes: "After-hours emergency call"
    },
    {
      id: "J008",
      title: "Sink Installation",
      client: "Green Restaurant",
      clientPhone: "(555) 555-6666",
      address: "555 Food St, Houston, TX 77008",
      technician: "Sarah Wilson",
      technicianId: "T002",
      status: "scheduled",
      jobType: "Plumbing",
      estimatedDuration: 120,
      scheduledDate: "2025-10-17",
      scheduledTime: "11:00",
      endTime: "13:00",
      value: 420.00,
      description: "Install new commercial kitchen sink",
      tags: ["Commercial", "Installation"],
      source: "Website",
      complexity: "medium",
      metroArea: "Greater Houston",
      notes: "Restaurant renovation project"
    },
    {
      id: "J009",
      title: "Water Heater Replacement",
      client: "Davis Family",
      clientPhone: "(555) 777-8888",
      address: "777 Maple Ave, Houston, TX 77009",
      technician: "Mike Rodriguez",
      technicianId: "T001",
      status: "scheduled",
      jobType: "Plumbing",
      estimatedDuration: 240,
      scheduledDate: "2025-10-20",
      scheduledTime: "08:00",
      endTime: "12:00",
      value: 1200.00,
      description: "Replace old water heater with new energy-efficient model",
      tags: ["Residential", "Replacement"],
      source: "Referral",
      complexity: "complex",
      metroArea: "Greater Houston",
      notes: "Energy efficiency upgrade"
    },
    {
      id: "J010",
      title: "Office HVAC Service",
      client: "Tech Startup Inc",
      clientPhone: "(555) 999-0000",
      address: "999 Innovation Dr, Houston, TX 77010",
      technician: "Sarah Wilson",
      technicianId: "T002",
      status: "completed",
      jobType: "HVAC",
      estimatedDuration: 180,
      scheduledDate: "2025-10-18",
      scheduledTime: "10:00",
      endTime: "13:00",
      value: 650.00,
      description: "Quarterly HVAC maintenance for office building",
      tags: ["Commercial", "Maintenance"],
      source: "Contract",
      complexity: "medium",
      metroArea: "Houston Metro",
      notes: "Tech startup - flexible scheduling"
    },
    {
      id: "J011",
      title: "Ceiling Fan Installation",
      client: "Rodriguez Home",
      clientPhone: "(555) 111-3333",
      address: "111 Sunset Blvd, Houston, TX 77011",
      technician: "David Chen",
      technicianId: "T003",
      status: "scheduled",
      jobType: "Electrical",
      estimatedDuration: 90,
      scheduledDate: "2025-10-22",
      scheduledTime: "14:00",
      endTime: "15:30",
      value: 280.00,
      description: "Install ceiling fan in master bedroom",
      tags: ["Residential", "Installation"],
      source: "Website",
      complexity: "simple",
      metroArea: "Greater Houston",
      notes: "New construction home"
    },
    {
      id: "J012",
      title: "Emergency Pipe Burst",
      client: "City Mall",
      clientPhone: "(555) 222-4444",
      address: "222 Shopping Center, Houston, TX 77012",
      technician: "Lisa Garcia",
      technicianId: "T004",
      status: "in-progress",
      jobType: "Plumbing",
      estimatedDuration: 120,
      scheduledDate: "2025-10-21",
      scheduledTime: "16:00",
      endTime: "18:00",
      value: 580.00,
      description: "Emergency pipe burst repair in food court",
      tags: ["Emergency", "Commercial"],
      source: "Emergency Call",
      complexity: "medium",
      metroArea: "Houston Metro",
      notes: "Mall emergency - high priority"
    },
    {
      id: "J013",
      title: "Boiler Inspection",
      client: "Metro Office Complex",
      clientPhone: "(555) 444-5555",
      address: "444 Business Park, Houston, TX 77013",
      technician: "Unassigned",
      technicianId: "unassigned",
      status: "unassigned",
      jobType: "HVAC",
      estimatedDuration: 120,
      scheduledDate: "2025-10-23",
      scheduledTime: "10:00",
      endTime: "12:00",
      value: 350.00,
      description: "Annual boiler inspection and maintenance",
      tags: ["Commercial", "Maintenance"],
      source: "Contract",
      complexity: "medium",
      metroArea: "Houston Metro",
      notes: "Needs technician assignment"
    },
    {
      id: "J014",
      title: "Smart Home Setup",
      client: "Johnson Family",
      clientPhone: "(555) 111-2222",
      address: "111 Tech Lane, Houston, TX 77016",
      technician: "Unassigned",
      technicianId: "unassigned",
      status: "unassigned",
      jobType: "Electrical",
      estimatedDuration: 240,
      scheduledDate: "2025-10-24",
      scheduledTime: "09:00",
      endTime: "13:00",
      value: 800.00,
      description: "Install smart home automation system",
      tags: ["Residential", "Installation"],
      source: "Website",
      complexity: "complex",
      metroArea: "Greater Houston",
      notes: "Waiting for technician assignment"
    },
    {
      id: "J015",
      title: "Pool Heater Repair",
      client: "Luxury Resort",
      clientPhone: "(555) 333-4444",
      address: "333 Resort Blvd, Houston, TX 77017",
      technician: "Unassigned",
      technicianId: "unassigned",
      status: "unassigned",
      jobType: "HVAC",
      estimatedDuration: 150,
      scheduledDate: "2025-10-19",
      scheduledTime: "14:00",
      endTime: "16:30",
      value: 650.00,
      description: "Pool heater not working, needs diagnostic and repair",
      tags: ["Commercial", "Repair"],
      source: "Emergency Call",
      complexity: "medium",
      metroArea: "Houston Metro",
      notes: "Urgent - needs immediate technician assignment"
    },
    {
      id: "J016",
      title: "HVAC Inspection",
      client: "Office Building A",
      clientPhone: "(555) 777-1111",
      address: "777 Business St, Houston, TX 77018",
      technician: "David Chen",
      technicianId: "T003",
      status: "scheduled",
      jobType: "HVAC",
      estimatedDuration: 90,
      scheduledDate: "2025-10-15",
      scheduledTime: "09:00",
      endTime: "10:30",
      value: 300.00,
      description: "Routine HVAC inspection for office building",
      tags: ["Commercial", "Inspection"],
      source: "Contract",
      complexity: "simple",
      metroArea: "Houston Metro",
      notes: "Same time as J001 - different technician"
    },
    {
      id: "J017",
      title: "Emergency Plumbing",
      client: "Restaurant Chain",
      clientPhone: "(555) 888-2222",
      address: "888 Food Court, Houston, TX 77019",
      technician: "Lisa Garcia",
      technicianId: "T004",
      status: "urgent",
      jobType: "Plumbing",
      estimatedDuration: 120,
      scheduledDate: "2025-10-15",
      scheduledTime: "10:30",
      endTime: "12:30",
      value: 450.00,
      description: "Emergency plumbing repair in restaurant",
      tags: ["Emergency", "Commercial"],
      source: "Emergency Call",
      complexity: "medium",
      metroArea: "Houston Metro",
      notes: "Overlaps with other jobs - different location"
    },
    {
      id: "J018",
      title: "Electrical Safety Check",
      client: "Safety Compliance Co",
      clientPhone: "(555) 999-3333",
      address: "999 Safety Blvd, Houston, TX 77020",
      technician: "Sarah Wilson",
      technicianId: "T002",
      status: "scheduled",
      jobType: "Electrical",
      estimatedDuration: 60,
      scheduledDate: "2025-10-15",
      scheduledTime: "09:00",
      endTime: "10:00",
      value: 200.00,
      description: "Electrical safety inspection and compliance check",
      tags: ["Commercial", "Safety"],
      source: "Contract",
      complexity: "simple",
      metroArea: "Houston Metro",
      notes: "Third job at 9:00 AM - testing multiple jobs"
    },
    {
      id: "J019",
      title: "Security System Install",
      client: "Secure Corp",
      clientPhone: "(555) 111-4444",
      address: "111 Security Ave, Houston, TX 77021",
      technician: "Mike Rodriguez",
      technicianId: "T001",
      status: "scheduled",
      jobType: "Electrical",
      estimatedDuration: 180,
      scheduledDate: "2025-10-15",
      scheduledTime: "09:00",
      endTime: "12:00",
      value: 750.00,
      description: "Install comprehensive security system",
      tags: ["Commercial", "Installation"],
      source: "Website",
      complexity: "complex",
      metroArea: "Houston Metro",
      notes: "Fourth job at 9:00 AM - testing 4+ jobs"
    },
    {
      id: "J020",
      title: "Fire Alarm Test",
      client: "Safety First Inc",
      clientPhone: "(555) 222-5555",
      address: "222 Fire Safety Rd, Houston, TX 77022",
      technician: "David Chen",
      technicianId: "T003",
      status: "scheduled",
      jobType: "Electrical",
      estimatedDuration: 45,
      scheduledDate: "2025-10-15",
      scheduledTime: "09:00",
      endTime: "09:45",
      value: 150.00,
      description: "Fire alarm system testing and certification",
      tags: ["Commercial", "Safety"],
      source: "Contract",
      complexity: "simple",
      metroArea: "Houston Metro",
      notes: "Fifth job at 9:00 AM - testing 5 jobs"
    },
    {
      id: "J021",
      title: "Network Setup",
      client: "Tech Solutions",
      clientPhone: "(555) 333-6666",
      address: "333 Network Dr, Houston, TX 77023",
      technician: "Lisa Garcia",
      technicianId: "T004",
      status: "scheduled",
      jobType: "Installation",
      estimatedDuration: 90,
      scheduledDate: "2025-10-15",
      scheduledTime: "09:00",
      endTime: "10:30",
      value: 400.00,
      description: "Network infrastructure setup and configuration",
      tags: ["Commercial", "Installation"],
      source: "Referral",
      complexity: "medium",
      metroArea: "Greater Houston",
      notes: "Sixth job at 9:00 AM - testing 6 jobs maximum"
    }
  ]