import { Source } from '../interface/source'

export const dummySources: Source[] = [
  {
    _id: '1',
    name: 'Company Website',
    description: 'Main company website lead generation',
    type: 'Website',
    url: 'https://company.com',
    isActive: true,
    priority: 1,
    color: '#3B82F6',
    icon: 'globe',
    metadata: {
      conversionRate: '2.5%',
      monthlyLeads: 150,
    },
    tenant_id: {
      _id: 'tenant1',
      name: 'WePro Company',
      username: 'wepro',
    },
    createdBy: {
      _id: 'user1',
      name: 'John Doe',
      username: 'johndoe',
    },
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
  },
  {
    _id: '2',
    name: 'Facebook Ads',
    description: 'Facebook advertising campaigns',
    type: 'Advertisement',
    url: 'https://facebook.com/ads',
    isActive: true,
    priority: 2,
    color: '#1877F2',
    icon: 'facebook',
    metadata: {
      adSpend: '$5000',
      cpc: '$2.50',
    },
    tenant_id: {
      _id: 'tenant1',
      name: 'WePro Company',
      username: 'wepro',
    },
    createdBy: {
      _id: 'user1',
      name: 'John Doe',
      username: 'johndoe',
    },
    createdAt: '2024-01-20T14:15:00Z',
    updatedAt: '2024-01-20T14:15:00Z',
  },
  {
    _id: '3',
    name: 'Google Ads',
    description: 'Google search and display advertising',
    type: 'Advertisement',
    url: 'https://ads.google.com',
    isActive: true,
    priority: 3,
    color: '#4285F4',
    icon: 'search',
    metadata: {
      adSpend: '$8000',
      cpc: '$3.20',
    },
    tenant_id: {
      _id: 'tenant1',
      name: 'WePro Company',
      username: 'wepro',
    },
    createdBy: {
      _id: 'user1',
      name: 'John Doe',
      username: 'johndoe',
    },
    createdAt: '2024-01-25T09:45:00Z',
    updatedAt: '2024-01-25T09:45:00Z',
  },
  {
    _id: '4',
    name: 'LinkedIn',
    description: 'LinkedIn professional networking',
    type: 'Social Media',
    url: 'https://linkedin.com',
    isActive: true,
    priority: 4,
    color: '#0A66C2',
    icon: 'linkedin',
    metadata: {
      followers: '5000',
      engagement: '3.2%',
    },
    tenant_id: {
      _id: 'tenant1',
      name: 'WePro Company',
      username: 'wepro',
    },
    createdBy: {
      _id: 'user1',
      name: 'John Doe',
      username: 'johndoe',
    },
    createdAt: '2024-02-01T11:20:00Z',
    updatedAt: '2024-02-01T11:20:00Z',
  },
  {
    _id: '5',
    name: 'Customer Referrals',
    description: 'Word of mouth and customer referrals',
    type: 'Referral',
    url: '',
    isActive: true,
    priority: 5,
    color: '#10B981',
    icon: 'users',
    metadata: {
      referralRate: '15%',
      avgReferralValue: '$2500',
    },
    tenant_id: {
      _id: 'tenant1',
      name: 'WePro Company',
      username: 'wepro',
    },
    createdBy: {
      _id: 'user1',
      name: 'John Doe',
      username: 'johndoe',
    },
    createdAt: '2024-02-05T16:30:00Z',
    updatedAt: '2024-02-05T16:30:00Z',
  },
  {
    _id: '6',
    name: 'Direct Contact',
    description: 'Direct phone calls and walk-ins',
    type: 'Direct',
    url: '',
    isActive: true,
    priority: 6,
    color: '#6B7280',
    icon: 'phone',
    metadata: {
      monthlyCalls: 75,
      conversionRate: '8%',
    },
    tenant_id: {
      _id: 'tenant1',
      name: 'WePro Company',
      username: 'wepro',
    },
    createdBy: {
      _id: 'user1',
      name: 'John Doe',
      username: 'johndoe',
    },
    createdAt: '2024-02-10T13:45:00Z',
    updatedAt: '2024-02-10T13:45:00Z',
  },
  {
    _id: '7',
    name: 'Instagram',
    description: 'Instagram social media marketing',
    type: 'Social Media',
    url: 'https://instagram.com/company',
    isActive: false,
    priority: 7,
    color: '#E4405F',
    icon: 'instagram',
    metadata: {
      followers: '12000',
      engagement: '4.1%',
    },
    tenant_id: {
      _id: 'tenant1',
      name: 'WePro Company',
      username: 'wepro',
    },
    createdBy: {
      _id: 'user1',
      name: 'John Doe',
      username: 'johndoe',
    },
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
  },
  {
    _id: '8',
    name: 'Trade Shows',
    description: 'Industry trade shows and events',
    type: 'Other',
    url: '',
    isActive: true,
    priority: 8,
    color: '#F59E0B',
    icon: 'calendar',
    metadata: {
      eventsPerYear: 6,
      avgLeadsPerEvent: 25,
    },
    tenant_id: {
      _id: 'tenant1',
      name: 'WePro Company',
      username: 'wepro',
    },
    createdBy: {
      _id: 'user1',
      name: 'John Doe',
      username: 'johndoe',
    },
    createdAt: '2024-02-20T15:30:00Z',
    updatedAt: '2024-02-20T15:30:00Z',
  },
]
